darknet_ros_topic: /darknet_ros/bounding_boxes
output_bbx3d_topic: /darknet_ros_3d/bounding_boxes
point_cloud_topic: /realsense/depth/color/points
working_frame: front_realsense
mininum_detection_thereshold: 1.0
minimum_probability: 0.35
interested_classes: ["chair", "person", "bottle", "table","bottle"] 